### ISSUE TITLE
Update the restify dependency to 6.0.1

### ISSUE THREAD

**Issue by KernelDev** [PhinCo/restify-await-promise#2]
As descriped here: https://david-dm.org/PhinCo/restify-await-promise?type=dev and here https://nodesecurity.io/advisories/restify_xss update your deps please.

Thank you

**Comment by darrenhaken** [comment]
Can you also do this because the current versions are marked as insecure deps:
https://david-dm.org/PhinCo/restify-await-promise?type=dev

**Comment by corim707** [comment]
Resolved as part of the 2.0.2 release.  Apologies for the delay but as these were dev dependencies only (not in the run time) this didn't get a priority for being fixed.
